services:
  mestrado:
    image: mestrado:cuda
    container_name: mestrado
    tty: true
    stdin_open: true
    working_dir: /workspace
    gpus: all
    volumes:
      - type: bind
        source: M:\
        target: /workspace
    command: bash
